### PR TITLE
Update contribution rules

### PR DESCRIPTION
**Pull request by salutis**

### CODE REVIEW

**Comment by salutis** [comment]
To review the new version of our contribution rules:
* Click _Files changed_ button
* Click _View_ button

**Comment by salutis** [comment]
@enfluid Could you please review the new rules?

The proposed new version:
https://github.com/enfluid/Public/blob/234785ee88ff1a9e492aa9ed8970411d9fbbeffb/CONTRIBUTING.md

**Comment by enfluid** [comment]
@salutis Looks good!

**Comment by salutis** [comment]
Thanks for the review. Merging.

**Pull request merged**
